### ISSUE TITLE
Plugin only works on server which use a panel like multicraft

### ISSUE THREAD

**Issue by liampearson96** [ModdedMinecraft/MMCReboot-Sponge#26]
For some reason this plugin doesnt work on servers that dont use multicraft. ive tried on my own dedicated server and the scheduled restarts dont actually restart the server. It just stops the server. Cheers

**Comment by yepidoodles** [comment]
Hey, I personally use [MineStart](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1264596-minestart-automatically-restart-crashed-minecraft) to restart my servers on my dedicated server, as it checks every x amount of time to see if the server is up, which is great alongside MMCReboot, which I use for my schedualled restarts. But if you're running Linux, I think you can set up something similar (I don't know anything about Linux, I'm using Windows).

**Comment by leelawd** [comment]
MMCReboot cannot fully restart the server  on its own due to it being a java plugin and not a server wrapper. When the server shuts down, the Java VM is shut down along with any information it holds so it would not be able to start back up from information provided by any plugin. 

The only way to achieve this is to use the methods in the above comment unfortunately.
