### ISSUE TITLE
Server only shutting down

### ISSUE THREAD

**Issue by Dinip** [ModdedMinecraft/MMCReboot-Sponge#30]
I'm running my server on a dedicated linux machine that starts with ./start.sh (start.sh contains all java arguments)
The problem is the server is not starting after a restart countdown.
Any solution?

**Comment by Fridtjof-DE** [comment]
Same for me

**Comment by leelawd** [comment]
Unfortunately there is nothing i can do inside the plugin to make it start back up again because the plugin no longer runs when the server shuts down and cannot do anything after that point, it requires an external program to recognise that it is no longer running

#26 might be able to help you out here.
